name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - archspec=0.2.1
  - asttokens=2.4.1
  - boltons=23.0.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.2.2
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - comm=0.2.1
  - conda=23.11.0
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=23.12.0
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - cryptography=41.0.7
  - debugpy=1.6.7
  - decorator=5.1.1
  - distro=1.8.0
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - fmt=9.1.0
  - icu=73.1
  - idna=3.4
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - ipykernel=6.29.2
  - ipython=8.21.0
  - jedi=0.19.1
  - jsonpatch=1.32
  - jsonpointer=2.1
  - jupyter_client=8.6.0
  - jupyter_core=5.7.1
  - krb5=1.20.1
  - libarchive=3.6.2
  - libcurl=8.4.0
  - libcxx=14.0.6
  - libedit=3.1.20230828
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.4
  - libiconv=1.16
  - libmamba=1.5.3
  - libmambapy=1.5.3
  - libnghttp2=1.57.0
  - libsodium=1.0.18
  - libsolv=0.7.24
  - libsqlite=3.45.1
  - libssh2=1.10.0
  - libxml2=2.10.4
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - matplotlib-inline=0.1.6
  - menuinst=2.0.1
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.2.1
  - packaging=23.1
  - parso=0.8.3
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=23.3.1
  - platformdirs=3.10.0
  - pluggy=1.0.0
  - prompt-toolkit=3.0.42
  - psutil=5.9.8
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.21
  - pygments=2.17.2
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.11.7
  - python-dateutil=2.8.2
  - python.app=3
  - python_abi=3.11
  - pyzmq=25.1.1
  - readline=8.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.31.0
  - ruamel.yaml=0.17.21
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tk=8.6.13
  - tornado=6.3.3
  - tqdm=4.65.0
  - traitlets=5.14.1
  - truststore=0.8.0
  - typing_extensions=4.9.0
  - urllib3=1.26.18
  - wcwidth=0.2.13
  - wheel=0.41.2
  - xz=5.4.5
  - yaml-cpp=0.8.0
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstandard=0.19.0
  - zstd=1.5.5
  - pip:
      - accelerate==0.28.0
      - aiofiles==23.2.1
      - altair==5.2.0
      - annotated-types==0.6.0
      - anyio==4.3.0
      - attrs==23.2.0
      - beautifulsoup4==4.12.3
      - bs4==0.0.2
      - click==8.1.7
      - cloudpickle==3.0.0
      - colorama==0.4.6
      - contourpy==1.2.0
      - cpm-kernels==1.0.11
      - cycler==0.12.1
      - farama-notifications==0.0.4
      - fastapi==0.110.0
      - ffmpy==0.3.2
      - filelock==3.13.1
      - fonttools==4.49.0
      - fsspec==2024.2.0
      - glog==0.3.1
      - gradio==4.21.0
      - gradio-client==0.12.0
      - gym==0.26.2
      - gym-notices==0.0.8
      - gymnasium==0.29.1
      - h11==0.14.0
      - httpcore==1.0.4
      - httpx==0.27.0
      - huggingface-hub==0.21.4
      - importlib-resources==6.3.0
      - jinja2==3.1.3
      - jsonlines==4.0.0
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.5
      - latex2mathml==3.77.0
      - lxml==5.1.0
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.8.3
      - mdtex2html==1.3.0
      - mdurl==0.1.2
      - mpmath==1.3.0
      - networkx==3.2.1
      - numpy==1.26.3
      - opencv-python==4.9.0.80
      - orjson==3.9.15
      - pandas==2.2.1
      - pillow==10.2.0
      - protobuf==4.24.4
      - pydantic==2.6.4
      - pydantic-core==2.16.3
      - pydub==0.25.1
      - pygame==2.5.2
      - pyparsing==3.1.2
      - python-gflags==3.1.2
      - python-multipart==0.0.9
      - pytz==2024.1
      - pyyaml==6.0.1
      - referencing==0.33.0
      - regex==2023.12.25
      - rich==13.7.1
      - rpds-py==0.18.0
      - ruff==0.3.2
      - safetensors==0.4.2
      - scipy==1.12.0
      - semantic-version==2.10.0
      - sentencepiece==0.2.0
      - shellingham==1.5.4
      - simpy==4.1.1
      - sniffio==1.3.1
      - soupsieve==2.5
      - starlette==0.36.3
      - sympy==1.12
      - tokenizers==0.13.3
      - tomlkit==0.12.0
      - toolz==0.12.1
      - torch==2.2.0
      - torchaudio==2.2.0
      - torchvision==0.17.0
      - transformers==4.30.2
      - typer==0.9.0
      - tzdata==2024.1
      - uvicorn==0.28.0
      - websockets==11.0.3
      - word2number==1.1
      - yunomi==0.3.0
